# Generated by Django 4.1.4 on 2022-12-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('details', models.TextField()),
                ('preout', models.TextField()),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('next_date', models.DateTimeField()),
            ],
        ),
    ]
